### ISSUE TITLE
rake test:plugins results in undefined method `on_load' for ActiveSupport:Module

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-codec-rubydebug#8]
For some reason, some other plugins must be loading ActiveSupport as a development dependency or something but that loaded version of ActiveSupport does not have the `on_load` method defined. see https://github.com/michaeldv/awesome_print/blob/d8aeb66b4b03dfb2cc1aec4e3187ced2f826d11f/lib/awesome_print.rb#L28-L29

Not sure how to attack this one. I am almost inclined to preemptively add a temporary dummy `ActiveSupport#on_load` to fix now-now while I file an issue upstream. 

```
  1) LogStash::Codecs::RubyDebug#encode should print beautiful hashes
     Failure/Error: subject { LogStash::Codecs::RubyDebug.new }
     NoMethodError:
       undefined method `on_load' for ActiveSupport:Module
     # ./vendor/bundle/jruby/1.9/gems/awesome_print-1.6.1/lib/awesome_print.rb:29:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-codec-rubydebug/lib/logstash/codecs/rubydebug.rb:1:in `(root)'
     # /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-codec-rubydebug/lib/logstash/codecs/rubydebug.rb:18:in `register'
     # ./logstash-core/lib/logstash/codecs/base.rb:15:in `initialize'
     # /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-codec-rubydebug/spec/codecs/rubydebug_spec.rb:7:in `subject'
     # /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-codec-rubydebug/spec/codecs/rubydebug_spec.rb:18:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by colinsurprenant** [comment]
For the record, I haven't filed any issue upstream as of yet.

**Comment by jsvd** [comment]
@colinsurprenant this should fix it https://github.com/michaeldv/awesome_print/pull/206/files

**Comment by jsvd** [comment]
as a workaround maybe explicitly set activesupport to be a dev dependency of this plugin and use a version that has on_load?

**Comment by ph** [comment]
Not a big fan of having an explicit dependency on activesupport.
This workaround should fix it no?
```ruby
unless ActiveSupport.respond_to?(:on_load)
  module  ActiveSupport
    def self.on_load(:action_view, &block)
    end
  end
end
```

**Comment by jsvd** [comment]
@ph it would only be a dev dependency so no harm there, but that leads to a silly yak shaving rabbit hole..

**Comment by ph** [comment]
@jsvd Probably just easier to have this patch "on" defined in the plugin spec.

**Comment by jsvd** [comment]
I am now convinced of that too :P

**Comment by colinsurprenant** [comment]
+1
